[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "test: marks tests as test (select with '-m test')",
]
addopts = "--verbose -rsxX -l --tb=short --strict-markers"
